### ISSUE TITLE
Training - NotImplementedError

### ISSUE THREAD

**Issue by thomaschhh** [bene-ges/nemo_compatible#15]
When running [`run_training.sh`](https://github.com/NVIDIA/NeMo/blob/main/examples/nlp/spellchecking_asr_customization/run_training.sh)

I get the following error:

NotImplementedError: Support for `validation_epoch_end` has been removed in v2.0.0. `SpellcheckingAsrCustomizationModel` implements this method. You can use the `on_validation_epoch_end` hook instead. To access outputs, save them in-memory as instance attributes. You can find migration examples in https://github.com/Lightning-AI/lightning/pull/16520.

My `pytorch-lightning` version is `2.0.9`. How did fix this on your side?

**Comment by bene-ges** [comment]
Thank you for this observation, I will try to fix it tomorrow

**Comment by bene-ges** [comment]
I created a [PR](https://github.com/NVIDIA/NeMo/pull/7924) in nemo, though it can take some time before they accept it.
You can look at the changes and test them yourself

**Comment by thomaschhh** [comment]
This looks good, thank you. 

Let's leave this open until they accept your PR.

**Comment by bene-ges** [comment]
@thomaschhh this PR was finally merged
