### ISSUE TITLE
Adding requirements-3.8.txt

### ISSUE THREAD

**Issue by Vubni** [bene-ges/nemo_compatible#21]
Why not add the requirements-3.8 file (3.8 of course corresponds to the Python version) so that no one makes the same mistakes as me? I have created the approximate contents of the file. If I missed something, I'm sorry
requirements-3.8.txt:
```
nemo_toolkit==1.21
torch
omegaconf
librosa==0.10.0
```
I've added exactly what I had errors about, but I've obviously missed a few required libraries. As soon as I can, I will edit the post and add the libraries that are required, but I will be glad if you can add them.

I really hope that you will accept my offer

I hope I'm suggesting the change correctly 😄? I don 't use github very often and I may be wrong

**Comment by bene-ges** [comment]
you can add as a pull request, thanks!
