### ISSUE TITLE
Potential Typo

### ISSUE THREAD

**Issue by thomaschhh** [bene-ges/nemo_compatible#4]
I am trying to walk through the steps mentioned at https://github.com/bene-ges/nemo_compatible/blob/main/scripts/nlp/en_spellmapper/README.md and am running into:

''FileNotFoundError: [Errno 2] No such file or directory: 'yago.uniq3'"

Might it be the case that it's supposed be "yago.uniq2" instead?
 
https://github.com/bene-ges/nemo_compatible/blob/194af660d9b6d3d578884048d40b524775fd10e8/scripts/nlp/en_spellmapper/dataset_preparation/run_g2p.sh#L21

**Comment by bene-ges** [comment]
Yes, you are right, thanks!

Btw, check [the newer version of the dataset](https://huggingface.co/datasets/bene-ges/wiki-en-asr-adapt) on my huggingface page, it contains some intermediate files too. 

Feel free to ask questions

**Comment by thomaschhh** [comment]
I think I found another typo:
https://github.com/bene-ges/nemo_compatible/blob/194af660d9b6d3d578884048d40b524775fd10e8/scripts/nlp/en_spellmapper/dataset_preparation/prepare_corpora_after_alignment.py#L246

Based on [Line 23](https://github.com/bene-ges/nemo_compatible/blob/194af660d9b6d3d578884048d40b524775fd10e8/scripts/nlp/en_spellmapper/dataset_preparation/prepare_corpora_after_alignment.py#L23) it should be `extract_giza_alignments` and not `extract_alignments`.

**Comment by bene-ges** [comment]
Thanks, fixed in `.sh` file

**Comment by thomaschhh** [comment]
https://github.com/bene-ges/nemo_compatible/blob/6c120745e8d42d406d4c19b14baecddf97500b92/scripts/nlp/en_spellmapper/dataset_preparation/preprocess_yago.sh#L1

I think `NEMO_PATH` should be `NEMO_COMPATIBLE_PATH`

**Comment by bene-ges** [comment]
Sure, fixed
