### ISSUE TITLE
Missing File decode_resample.py

### ISSUE THREAD

**Issue by thomaschhh** [bene-ges/nemo_compatible#5]
It seems like _decode_resample.py_ is missing in the NeMo repo, or am I missing something?

https://github.com/bene-ges/nemo_compatible/blob/194af660d9b6d3d578884048d40b524775fd10e8/scripts/nlp/en_spellmapper/dataset_preparation/run_tts_and_asr.sh#L18

**Comment by bene-ges** [comment]
@thomaschhh , sorry, you don't need it, just comment this line with decode_resample.py,
the audios are already in 16000Hz
